- client/syntaxes/bitbake.tmLanguage.json
Improve existing syntax highlighting
> Feat: Improve existing syntax highlighting

- client/src/BitBakeDocumentSemanticTokensProvider.ts
- client/src/extension.ts
- client/syntaxes/bitbake.tmLanguage.json
1. Match function and variable declarations
2. Match function and variable references
3. References are matched only if they are declared first
4. Currently it doesn't care about the scope, tokens are generated as long as they are matched by the regex
> Feat: Implement basic semantic highlighting for functions and variables

- server/src/server.ts
documents.listen(connection) (TextDocuments) overwrites the connection's handlers relatives to documents. Handlers such as `connection.onDidOpenTextDocument` or `connectiononDidChangeTextDocument` were not working anymore, since they were respectively overwritten by `documents.onDidOpen` and `documents.onDidChangeContent`, for which we had not assigned any listener function. This was breaking the hover, for example.
This PR also reintroduces TextDocumentSyncKind.Incremental.
> Fix: Fix documents' handlers

- server/src/BitBakeProjectScanner.ts
- server/src/OutputParser.ts
- server/src/ProblemsContainer.ts
- server/src/server.ts
- Lines with parsing errors are underlined
- Use spawnSync instead of execSync
- Improve handling of errors for child_process
- Simplify parts of code
- Move 'rescanProject' to onDidChangeConfiguration
> Fix: Fix parseAllRecipes

- .vscode/settings.json
This setting enables auto fix for eslint errors on save
> Chore: Add the setting to auto fix eslint errors on save

- .eslintignore
- client/package.json
- jest.config.js
- package.json
- server/src/__tests__/test.test.ts
Removed mocha library and added Jest.
Most settings are from `bash-language-server`.
Added a `test.test.ts` for verifying the functionality.
In order to have a complete test suite for this **TS** project. we seem to need additional libraries.
> Add Jest test framework

- server/src/SymbolScanner.ts
I encountered a read file error on Windows, so I made the following changes:
1. Remove the `throw` in the `catch` block because the upper call stack doesn't handle it. 
2. Use `decodeURIComponent` to decode URLs. This will correctly decode Windows URLs (e.g. `d%3A/folder` -> `d:/folder`)
From my understanding of this SymbolScanner, some functionalities could be moved to the Analyzer (tree-sitter). For now, let's keep it as is.
> Fix: SymbolScanner fail to read URLs  on Windows

- client/src/language/languageClient.ts
- server/src/server.ts
The `.conf` files should always be associated with `bitbake` language mode as long as there is no other extension causing the conflict. Currently, this extension is known to cause such conflict: [Txt Syntax](https://github.com/xshrim/vscode-txt-syntax/blob/3e5851b4a4eaf6a0e5fc5281fa29f1f68cd5d591/src/extension.js#L103)
I prefer to let users be aware of this situation rather than attempting to compete against another extension to set the language mode.
> Chore: Add request to verify conf files association

- server/package.json
Seems like the files automatically include the `path` and `fs` from `@types/node` at root `package.json`. So I don't think the obsolete ones from server `package.json` are actually used. ~~However, I didn't find a good replacement for `find`, so I used the `readdir` from `fs` to achieve the similar results.~~
> Use path, fs from @types/node

- client/syntaxes/bitbake.tmLanguage.json
- client/test/grammars/snaps/strings.bb
- client/test/grammars/test-cases/nested-patterns.bb
- client/test/grammars/test-cases/strings.bb
A scope is explicitly assigned to the `\"` to avoid breaking the highlighting inside the string.  The rule for content within `[]` is also removed. As you can see the highlighting after `depends = []` is broken.
~~we will eventually have an embedded language service that handles the code within python/shell functions~~ temporary fixes like this will be applied for now. We are planning to use tree-sitter to provider extra support on syntax highlighting.
> Fix: (\") breaks the highlighting inside the string & broken grammar rule related to []

- server/src/BitBakeProjectScanner.ts
- server/src/ContextHandler.ts
- server/src/OutputParser.ts
- server/src/ServerNotificationManager.ts
- server/src/connectionHandlers/onDefinition.ts
- server/src/server.ts
- server/src/tree-sitter/analyzer.ts
1.`OutputParser` and `serverNotificationManager` don't need to instantiate with `connection`. The connection can be set on start up. Plus, some classes only need one instance, I export one from the file where the class is defined to make sure everywhere else can reference the same instance.
~~2.`documentAsTextMap` and Analyzer's `uriToAnalyzedDocument` have some similarities. They can be merged later. For now, they can both be members of the Analyzer~~
2. Analyzer's `uriToAnalyzedDocument` already has a TextDocument object, so I use it to replace the `documentAsTextMap`
3. `onDefinitionHandler` is put in its own file for better testing
> Refactor: Remove connection from class members etc

- server/src/BitBakeDocScanner.ts
- server/src/__tests__/completions.test.ts
- server/src/__tests__/fixtures/completion.bb
- server/src/completions/bitbake-operator.ts
- server/src/completions/snippet-utils.ts
- server/src/completions/variable-flags.ts
- server/src/connectionHandlers/onCompletion.ts
- server/src/server.ts
- server/src/tree-sitter/analyzer.ts
Override syntax completion will be triggered by typing `:` and variable flag completion will be triggered by typing `[` as long as they follow an `identifier` which is a type defined by the tree-sitter-bitbake. 
Only a list of minimum items is added as I didn't find the complete docs for them. The mechanics of adding completion items are ready for review.
sample result:
> Add completion items for operators and variable flags

- server/src/BitBakeDocScanner.ts
- server/src/ContextHandler.ts
- server/src/__tests__/definition.test.ts
- server/src/__tests__/fixtures/definition.bb
- server/src/__tests__/fixtures/fixtures.ts
- server/src/__tests__/fixtures/hover.bb
- server/src/__tests__/hover.test.ts
- server/src/completions/snippet-utils.ts
- server/src/connectionHandlers/onCompletion.ts
- server/src/connectionHandlers/onDefinition.ts
- server/src/connectionHandlers/onHover.ts
- server/src/server.ts
- server/src/tree-sitter/analyzer.ts
- server/src/tree-sitter/declarations.ts
- server/src/tree-sitter/parser.ts
- server/src/tree-sitter/utils.ts
- server/src/utils/async.ts
- server/src/utils/lsp.ts
Please read the commit messages for the details in sequence.
> Various changes: enhanced current features, added tests, fixed bugs and more

- server/src/server.ts
The default logger level is none, so all logs in onInitialize (which fires before `onDidChangeConfiguration`) won't show. Thus, set a temporary logger level to enable the logs in this event. It will then be overridden by extension settings later in `onDidChangeConfiguration`
> Set logger level in onInitialize event

- client/src/language/languageClient.ts
- client/syntaxes/bitbake.tmLanguage.json
- server/src/__tests__/completions.test.ts
- server/src/completions/snippet-utils.ts
- server/src/connectionHandlers/onCompletion.ts
- server/src/tree-sitter/analyzer.ts
1. Add a rule to not highlight keywords if they follow or are followed by any special character. (`\b` only handles letters, digits and underscore)
Not all keywords are covered consider the possibility of inline code (Is that a case?)
2. Enable the completion in the middle of typing override/operator syntax
3. Remove the code that sets the editor quick suggestion for strings to true. Because this also disabled word-based suggestion (Simple words that are ever typed in the document). The context-based suggestion is disabled using the tree-sitter.
4. Add variable expansion check to limit completion items in it. Currently, the keywords won't show anymore. Note that the current tree-sitter won't treat `"${}"` as variable expansion. @deribaucourt And I think it is a rare case that people …
> Various updates and fixes on completion

- server/src/connectionHandlers/onCompletion.ts
The overrides are scanned using no specific recipe. The corresponding package override, pn-defaultpkgname does not exist in this case. Commonly, ${PN} is used instead.
> Fix: Replace pn-defaultpkgname with ${PN}

- scripts/fetch-docs.sh
- server/src/BitBakeDocScanner.ts
- server/src/__tests__/completions.test.ts
- server/src/__tests__/fixtures/hover.bb
- server/src/__tests__/hover.test.ts
- server/src/completions/snippet-utils.ts
- server/src/connectionHandlers/onCompletion.ts
- server/src/connectionHandlers/onHover.ts
- server/src/tree-sitter/analyzer.ts
1. Refactored the bitbakeDocScanner. It won't store completion items. The conversion happens in `onCompletion` handler.
2. Added variables from yocto docs.
3. Added hover definition for yocto tasks.
4. Updated the tests.
> Refactor, add variables from yocto docs, add hover definition for yocto docs, etc

- server/src/__tests__/fixtures/hover.bb
- server/src/__tests__/hover.test.ts
- server/src/connectionHandlers/onHover.ts
1. Add hover definition on variables in **variable expansion syntax**
2. Hover definition on variables inside the functions is on hold until the embedded language service is done.
~~This branch rebased `Feature-10412-add-variables-from-yocto-docs` so it should be merged after [PR/59](https://github.com/savoirfairelinux/vscode-bitbake/pull/59)~~ _merged_
> Feature 10418 add hover definition for variable references

- client/package.json
- client/syntaxes/bitbake.tmLanguage.json
- client/test/grammars/snaps/strings.bb
- client/test/grammars/snaps/variables.bb
- client/test/grammars/test-cases/functions.bb
- client/test/grammars/test-cases/strings.bb
- client/test/grammars/test-cases/variables.bb
- server/src/__tests__/fixtures/fixtures.ts
- server/src/__tests__/fixtures/semanticTokens.bb
- server/src/__tests__/semanticTokens.test.ts
- server/src/semanticTokensProvider.ts
- server/src/server.ts
- server/src/tree-sitter/analyzer.ts
- server/src/tree-sitter/utils.ts
1. Enabled semanticTokensProvider at the server side.
Example results:
3. Fixed the bug where non-inline-python syntax is highlighted as python
Example results:
With `@`
Without `@`
4. Added and updated related tests
> Enable semanticTokensProvider, fix bug, update tests etc

- client/src/language/languageClient.ts
- client/src/language/middlewareCompletion.ts
- client/src/language/middlewareHover.ts
- client/src/language/utils.ts
- client/src/lib/src/types/embedded-languages.ts
- server/src/__tests__/embedded-languages.test.ts
- server/src/embedded-languages/bash-support.ts
- server/src/embedded-languages/documents-manager.ts
- server/src/embedded-languages/python-support.ts
- server/src/embedded-languages/utils.ts
- server/src/tree-sitter/analyzer.ts
- server/src/tree-sitter/declarations.ts
- server/src/tree-sitter/utils.ts
This includes various new functionalities:
- Add support for inline python
- Handle imports of 'bb', 'd', 'e' and 'os'
- Fix some syntaxes that were not handled properly
They come together because my intent was to make sure I was able to map properly the positions between the embedded language documents and the original documents, once they are heavily modified.
Unfortunately, the embedded language support is still not as smooth as I'd like to. For example, tree-sitter-bitbake has a couple of bugs that will suddenly break the parsing in many unexpected ways (https://github.com/amaanq/tree-sitter-bitbake/issues/10, https://github.com/amaanq/tree-sitter-bitbake/issues/12). It seems it will also break once in a while as I type bitbake code. These issues will be addressed later, as the …
> Improve embedded language support

- client/src/language/middlewareCompletion.ts
- client/src/language/middlewareHover.ts
- client/src/lib/src/types/requests.ts
The middlewares were expecting to receive `undefined` when the cursor was outside Bash or Python regions. For unknown reasons, they are receiving `null`.
This fix hover and completions for regions outside of Bash and Python regions (sorry I broke it). For unknown reasons, this also fix completion inside Python regions (it was still working for bash regions, and hover was still working for both).
> Fix: Middlewares also expect null regions

- integration-tests/project-folder/.vscode/settings.json
- server/src/__tests__/hover.test.ts
- server/src/connectionHandlers/onHover.ts
The hover definition should show for Yocto variables and should show the one for Yocto in case of duplicate variable names.
> Bug 13349 missing hover information

- client/src/language/utils.ts
workspace.openTextDocument would not update the document when and new version get saved, which had for result to give a non-updated position.
> Fix: Embedded language position updates properly

- client/src/lib/src/BitbakeSettings.ts
- client/src/lib/src/__tests__/driver/bitbake-settings.test.ts
Settings like pathToBitbakeFolder should use "${workspaceFolder}" to point to relative URIs. However if the user uses a relative path like "./", the language server did resolve it properly, but not the client. We now set the working directory to the workspace folder to be consistent.
This does not produce unintended side effects according to our tests.
> Fix: Change working directory for relative paths settings

- client/src/extension.ts
The user may want to disable the bitbake error popup for a specific workspace but he should be reminded of the error popup when he opens another workspace.
> Fix: Disable bitbake error popup per workspace instead of globally

- client/syntaxes/bitbake.tmLanguage.json
- client/test/grammars/snaps/strings.bb
- client/test/grammars/test-cases/strings.bb
> Fix incorrect highlight on escaped quotes outside the strings

- README.md
Follows the Linux Foundation's recommendations.
> Chore: Rename master branch to main

- client/src/lib/src/BitbakeDriver.ts
- client/src/lib/src/BitbakeSettings.ts
- client/src/lib/src/__tests__/driver/bitbake-driver.test.ts
- client/src/ui/BitbakeTaskProvider.ts
- integration-tests/project-folder/.vscode/settings.json
- server/src/BitBakeProjectScanner.ts
- server/src/__tests__/scanner.test.ts
- server/src/server.ts
Calling bitbake through a docker commandWrapper is possible except we get broken pipe errors because of the way the bitbake server forks. This PR refactors the way we call bitbake in order to serialize them.
> Docker wrapper support

- client/syntaxes/bitbake.tmLanguage.json
- client/test/grammars/snaps/strings.bb
- client/test/grammars/test-cases/strings.bb
This handles the highlighting for triple quotes when the highlighting from the embedded service is not available.
Issue: https://github.com/yoctoproject/vscode-bitbake/issues/3
> Fix: Handle triple quotes correctly

- server/src/__tests__/analyzer.test.ts
- server/src/__tests__/completions.test.ts
- server/src/__tests__/definition.test.ts
- server/src/__tests__/fixtures/bbclass/baz.bbclass
- server/src/__tests__/fixtures/definition.bb
- server/src/__tests__/fixtures/directive.bb
- server/src/__tests__/fixtures/fixtures.ts
- server/src/__tests__/fixtures/inc/bar.inc
- server/src/__tests__/fixtures/inc/foo.inc
- server/src/__tests__/hover.test.ts
- server/src/__tests__/semanticTokens.test.ts
- server/src/connectionHandlers/onCompletion.ts
- server/src/connectionHandlers/onDefinition.ts
- server/src/tree-sitter/analyzer.ts
- server/src/tree-sitter/declarations.ts
What `SymbolScanner` was doing:
1. Associate a new instance of it to the file when it is opened or has content changed.
2. Scan for the file in directives (**include**, **inherit** and **require**) and get the file paths, then store the file paths and their content.
3. Recursively repeat the step 2 for each file scanned.
4. When the scan is complete, Loop the stored file paths and content in step 2 to get the symbols **_(Declared variables and exported variables. e.g. `VAR = 'var'` and `export VAR = '123'`)_** using RegEx.
What I am trying to do here:
1. Without changing the goal of the original `SymbolScanner`, use the tree-sitter instead of the RegEx.
2. Move all implementations to the `analyzer`.
3. Optimized the file reading since SymbolScanner was doing a lot of the reads while the …
> Implement and optimize symbol scanner in Analyzer

- server/src/__tests__/embedded-languages.test.ts
- server/src/embedded-languages/python-support.ts
Previously, BitBake's modules were imported only when they were fully typed in the code. It made completion impossible before the user had typed them.
Now they are all imported in a way that should reflect BitBake's specification.
> Chore: Import BitBake Python modules from the beginning
